/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUtilisateursRouteImport } from './routes/_authenticated/utilisateurs'
import { Route as AuthenticatedRetenuesRouteImport } from './routes/_authenticated/retenues'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPaiementsRouteImport } from './routes/_authenticated/paiements'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedFournisseursRouteImport } from './routes/_authenticated/fournisseurs'
import { Route as AuthenticatedFacturesRouteImport } from './routes/_authenticated/factures'
import { Route as AuthenticatedDevisRouteImport } from './routes/_authenticated/devis'
import { Route as AuthenticatedDepensesRouteImport } from './routes/_authenticated/depenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAchatsRouteImport } from './routes/_authenticated/achats'
import { Route as AuthenticatedFacturesIndexRouteImport } from './routes/_authenticated/factures.index'
import { Route as AuthenticatedDevisIndexRouteImport } from './routes/_authenticated/devis.index'
import { Route as AuthenticatedFacturesNouveauRouteImport } from './routes/_authenticated/factures.nouveau'
import { Route as AuthenticatedFacturesIdRouteImport } from './routes/_authenticated/factures.$id'
import { Route as AuthenticatedDevisNouveauRouteImport } from './routes/_authenticated/devis.nouveau'
import { Route as AuthenticatedDevisIdRouteImport } from './routes/_authenticated/devis.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUtilisateursRoute =
  AuthenticatedUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRetenuesRoute = AuthenticatedRetenuesRouteImport.update({
  id: '/retenues',
  path: '/retenues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaiementsRoute = AuthenticatedPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFournisseursRoute =
  AuthenticatedFournisseursRouteImport.update({
    id: '/fournisseurs',
    path: '/fournisseurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturesRoute = AuthenticatedFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevisRoute = AuthenticatedDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepensesRoute = AuthenticatedDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchatsRoute = AuthenticatedAchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturesIndexRoute =
  AuthenticatedFacturesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFacturesRoute,
  } as any)
const AuthenticatedDevisIndexRoute = AuthenticatedDevisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDevisRoute,
} as any)
const AuthenticatedFacturesNouveauRoute =
  AuthenticatedFacturesNouveauRouteImport.update({
    id: '/nouveau',
    path: '/nouveau',
    getParentRoute: () => AuthenticatedFacturesRoute,
  } as any)
const AuthenticatedFacturesIdRoute = AuthenticatedFacturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFacturesRoute,
} as any)
const AuthenticatedDevisNouveauRoute =
  AuthenticatedDevisNouveauRouteImport.update({
    id: '/nouveau',
    path: '/nouveau',
    getParentRoute: () => AuthenticatedDevisRoute,
  } as any)
const AuthenticatedDevisIdRoute = AuthenticatedDevisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDevisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achats': typeof AuthenticatedAchatsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/devis': typeof AuthenticatedDevisRouteWithChildren
  '/factures': typeof AuthenticatedFacturesRouteWithChildren
  '/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/retenues': typeof AuthenticatedRetenuesRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/devis/nouveau': typeof AuthenticatedDevisNouveauRoute
  '/factures/$id': typeof AuthenticatedFacturesIdRoute
  '/factures/nouveau': typeof AuthenticatedFacturesNouveauRoute
  '/devis/': typeof AuthenticatedDevisIndexRoute
  '/factures/': typeof AuthenticatedFacturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achats': typeof AuthenticatedAchatsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depenses': typeof AuthenticatedDepensesRoute
  '/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/paiements': typeof AuthenticatedPaiementsRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/retenues': typeof AuthenticatedRetenuesRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/devis/$id': typeof AuthenticatedDevisIdRoute
  '/devis/nouveau': typeof AuthenticatedDevisNouveauRoute
  '/factures/$id': typeof AuthenticatedFacturesIdRoute
  '/factures/nouveau': typeof AuthenticatedFacturesNouveauRoute
  '/devis': typeof AuthenticatedDevisIndexRoute
  '/factures': typeof AuthenticatedFacturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achats': typeof AuthenticatedAchatsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/depenses': typeof AuthenticatedDepensesRoute
  '/_authenticated/devis': typeof AuthenticatedDevisRouteWithChildren
  '/_authenticated/factures': typeof AuthenticatedFacturesRouteWithChildren
  '/_authenticated/fournisseurs': typeof AuthenticatedFournisseursRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/paiements': typeof AuthenticatedPaiementsRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/retenues': typeof AuthenticatedRetenuesRoute
  '/_authenticated/utilisateurs': typeof AuthenticatedUtilisateursRoute
  '/_authenticated/devis/$id': typeof AuthenticatedDevisIdRoute
  '/_authenticated/devis/nouveau': typeof AuthenticatedDevisNouveauRoute
  '/_authenticated/factures/$id': typeof AuthenticatedFacturesIdRoute
  '/_authenticated/factures/nouveau': typeof AuthenticatedFacturesNouveauRoute
  '/_authenticated/devis/': typeof AuthenticatedDevisIndexRoute
  '/_authenticated/factures/': typeof AuthenticatedFacturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achats'
    | '/clients'
    | '/dashboard'
    | '/depenses'
    | '/devis'
    | '/factures'
    | '/fournisseurs'
    | '/journal'
    | '/paiements'
    | '/parametres'
    | '/profil'
    | '/retenues'
    | '/utilisateurs'
    | '/devis/$id'
    | '/devis/nouveau'
    | '/factures/$id'
    | '/factures/nouveau'
    | '/devis/'
    | '/factures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achats'
    | '/clients'
    | '/dashboard'
    | '/depenses'
    | '/fournisseurs'
    | '/journal'
    | '/paiements'
    | '/parametres'
    | '/profil'
    | '/retenues'
    | '/utilisateurs'
    | '/devis/$id'
    | '/devis/nouveau'
    | '/factures/$id'
    | '/factures/nouveau'
    | '/devis'
    | '/factures'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achats'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/depenses'
    | '/_authenticated/devis'
    | '/_authenticated/factures'
    | '/_authenticated/fournisseurs'
    | '/_authenticated/journal'
    | '/_authenticated/paiements'
    | '/_authenticated/parametres'
    | '/_authenticated/profil'
    | '/_authenticated/retenues'
    | '/_authenticated/utilisateurs'
    | '/_authenticated/devis/$id'
    | '/_authenticated/devis/nouveau'
    | '/_authenticated/factures/$id'
    | '/_authenticated/factures/nouveau'
    | '/_authenticated/devis/'
    | '/_authenticated/factures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/utilisateurs': {
      id: '/_authenticated/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthenticatedUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retenues': {
      id: '/_authenticated/retenues'
      path: '/retenues'
      fullPath: '/retenues'
      preLoaderRoute: typeof AuthenticatedRetenuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paiements': {
      id: '/_authenticated/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof AuthenticatedPaiementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fournisseurs': {
      id: '/_authenticated/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AuthenticatedFournisseursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factures': {
      id: '/_authenticated/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof AuthenticatedFacturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devis': {
      id: '/_authenticated/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof AuthenticatedDevisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depenses': {
      id: '/_authenticated/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof AuthenticatedDepensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achats': {
      id: '/_authenticated/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AuthenticatedAchatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factures/': {
      id: '/_authenticated/factures/'
      path: '/'
      fullPath: '/factures/'
      preLoaderRoute: typeof AuthenticatedFacturesIndexRouteImport
      parentRoute: typeof AuthenticatedFacturesRoute
    }
    '/_authenticated/devis/': {
      id: '/_authenticated/devis/'
      path: '/'
      fullPath: '/devis/'
      preLoaderRoute: typeof AuthenticatedDevisIndexRouteImport
      parentRoute: typeof AuthenticatedDevisRoute
    }
    '/_authenticated/factures/nouveau': {
      id: '/_authenticated/factures/nouveau'
      path: '/nouveau'
      fullPath: '/factures/nouveau'
      preLoaderRoute: typeof AuthenticatedFacturesNouveauRouteImport
      parentRoute: typeof AuthenticatedFacturesRoute
    }
    '/_authenticated/factures/$id': {
      id: '/_authenticated/factures/$id'
      path: '/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof AuthenticatedFacturesIdRouteImport
      parentRoute: typeof AuthenticatedFacturesRoute
    }
    '/_authenticated/devis/nouveau': {
      id: '/_authenticated/devis/nouveau'
      path: '/nouveau'
      fullPath: '/devis/nouveau'
      preLoaderRoute: typeof AuthenticatedDevisNouveauRouteImport
      parentRoute: typeof AuthenticatedDevisRoute
    }
    '/_authenticated/devis/$id': {
      id: '/_authenticated/devis/$id'
      path: '/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof AuthenticatedDevisIdRouteImport
      parentRoute: typeof AuthenticatedDevisRoute
    }
  }
}

interface AuthenticatedDevisRouteChildren {
  AuthenticatedDevisIdRoute: typeof AuthenticatedDevisIdRoute
  AuthenticatedDevisNouveauRoute: typeof AuthenticatedDevisNouveauRoute
  AuthenticatedDevisIndexRoute: typeof AuthenticatedDevisIndexRoute
}

const AuthenticatedDevisRouteChildren: AuthenticatedDevisRouteChildren = {
  AuthenticatedDevisIdRoute: AuthenticatedDevisIdRoute,
  AuthenticatedDevisNouveauRoute: AuthenticatedDevisNouveauRoute,
  AuthenticatedDevisIndexRoute: AuthenticatedDevisIndexRoute,
}

const AuthenticatedDevisRouteWithChildren =
  AuthenticatedDevisRoute._addFileChildren(AuthenticatedDevisRouteChildren)

interface AuthenticatedFacturesRouteChildren {
  AuthenticatedFacturesIdRoute: typeof AuthenticatedFacturesIdRoute
  AuthenticatedFacturesNouveauRoute: typeof AuthenticatedFacturesNouveauRoute
  AuthenticatedFacturesIndexRoute: typeof AuthenticatedFacturesIndexRoute
}

const AuthenticatedFacturesRouteChildren: AuthenticatedFacturesRouteChildren = {
  AuthenticatedFacturesIdRoute: AuthenticatedFacturesIdRoute,
  AuthenticatedFacturesNouveauRoute: AuthenticatedFacturesNouveauRoute,
  AuthenticatedFacturesIndexRoute: AuthenticatedFacturesIndexRoute,
}

const AuthenticatedFacturesRouteWithChildren =
  AuthenticatedFacturesRoute._addFileChildren(
    AuthenticatedFacturesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchatsRoute: typeof AuthenticatedAchatsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepensesRoute: typeof AuthenticatedDepensesRoute
  AuthenticatedDevisRoute: typeof AuthenticatedDevisRouteWithChildren
  AuthenticatedFacturesRoute: typeof AuthenticatedFacturesRouteWithChildren
  AuthenticatedFournisseursRoute: typeof AuthenticatedFournisseursRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedPaiementsRoute: typeof AuthenticatedPaiementsRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRetenuesRoute: typeof AuthenticatedRetenuesRoute
  AuthenticatedUtilisateursRoute: typeof AuthenticatedUtilisateursRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchatsRoute: AuthenticatedAchatsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepensesRoute: AuthenticatedDepensesRoute,
  AuthenticatedDevisRoute: AuthenticatedDevisRouteWithChildren,
  AuthenticatedFacturesRoute: AuthenticatedFacturesRouteWithChildren,
  AuthenticatedFournisseursRoute: AuthenticatedFournisseursRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedPaiementsRoute: AuthenticatedPaiementsRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRetenuesRoute: AuthenticatedRetenuesRoute,
  AuthenticatedUtilisateursRoute: AuthenticatedUtilisateursRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
