// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 🔹 Cache pour éviter les recréations multiples
let _supabaseInstance: SupabaseClient<Database> | null = null;
let _isCreating = false;

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// 🔹 Storage avec fallback et sans erreurs
function createSecureStorage() {
  if (typeof window === 'undefined') return undefined;

  try {
    // Tester si sessionStorage est disponible
    const testKey = '__supabase_test__';
    sessionStorage.setItem(testKey, 'test');
    sessionStorage.removeItem(testKey);

    return {
      getItem: (key: string) => {
        try { return sessionStorage.getItem(key); } catch { return null; }
      },
      setItem: (key: string, value: string) => {
        try { sessionStorage.setItem(key, value); } catch { /* ignore */ }
      },
      removeItem: (key: string) => {
        try { sessionStorage.removeItem(key); } catch { /* ignore */ }
      }
    };
  } catch {
    // Fallback vers un storage en mémoire
    const memoryStorage = new Map<string, string>();
    return {
      getItem: (key: string) => memoryStorage.get(key) || null,
      setItem: (key: string, value: string) => { memoryStorage.set(key, value); },
      removeItem: (key: string) => { memoryStorage.delete(key); }
    };
  }
}

function createSupabaseClient(): SupabaseClient<Database> {
  // 🔹 Si déjà créé, retourner l'instance existante
  if (_supabaseInstance) return _supabaseInstance;
  if (_isCreating) {
    // Attendre que la création soit terminée
    return _supabaseInstance!;
  }

  _isCreating = true;

  try {
    const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    _supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: createSecureStorage(),
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        flowType: 'pkce',
      }
    });

    return _supabaseInstance;
  } finally {
    _isCreating = false;
  }
}

// 🔹 Exporter une instance unique
export const supabase = createSupabaseClient();

// 🔹 Fonction de nettoyage
export function clearSupabaseSession() {
  try {
    if (typeof window !== 'undefined') {
      const keys = Object.keys(sessionStorage);
      keys.forEach(key => {
        if (key.startsWith('sb-')) {
          sessionStorage.removeItem(key);
        }
      });
    }
  } catch {
    // Silencieux
  }
}